/**
 * `npm run charter:extract` — every archived charter PDF into a structured
 * DRAFT, one file per document, under `inventory/charter-transcripts/`.
 *
 * ★ TAGO-202 criterion 5: this tool cannot produce a shippable page. What it
 * writes is a draft in an inventory folder that nothing renders, marked with
 * the confidence the extraction actually earned, and a page is generated from
 * it only after a human has read the draft against the document.
 *
 * It never rounds, reformats, merges or modernises a figure. The only
 * transformation applied to any string that came out of a PDF is collapsing
 * poppler's inter-word gaps to single spaces.
 *
 * Rerunning is safe and deterministic: same PDF in, byte-identical YAML out.
 */

import { createHash } from 'node:crypto';
import { mkdirSync, readFileSync, readdirSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import yaml from 'js-yaml';

import { extractDocument } from './charter-values.mjs';
import { documentStem } from './charter-parse.mjs';

const ROOT = path.resolve(import.meta.dirname, '..');
const ARCHIVE = path.join(ROOT, 'sources', 'charter');
const OUT = path.join(ROOT, 'inventory', 'charter-transcripts');
const INVENTORY = path.join(ROOT, 'inventory');

const BANNER = `# Generated by scripts/charter-extract.mjs — do not edit by hand.
#
# A DRAFT, not content. Nothing here is published, and nothing here is verified.
# Every string that came out of the PDF is byte-identical to the PDF; see
# scripts/charter-values.mjs for what the extractor will and will not claim.
`;

const sha256 = buffer => createHash('sha256').update(buffer).digest('hex');

/**
 * Stable ids, matching `charter-parse.mjs` exactly.
 *
 * The ordinal is the service's position within its document and section. NOT
 * the charter's printed number, which collides: across the real archive that
 * yields 159 distinct keys for 167 services.
 */
function withIds(file, services) {
  const stem = documentStem(file);
  const counts = new Map();
  return services.map(service => {
    const ordinal = (counts.get(service.section) ?? 0) + 1;
    counts.set(service.section, ordinal);
    return { id: `${stem}#${service.section}-${ordinal}`, ...service };
  });
}

function main() {
  mkdirSync(OUT, { recursive: true });

  const files = readdirSync(ARCHIVE)
    .filter(name => name.toLowerCase().endsWith('.pdf'))
    .sort();

  const summary = [];

  for (const file of files) {
    const full = path.join(ARCHIVE, file);
    const services = withIds(file, extractDocument(full));

    const document = {
      document: file,
      sha256: sha256(readFileSync(full)),
      extractedAt: process.env.CHARTER_EXTRACT_DATE ?? '2026-08-10',
      serviceCount: {
        total: services.length,
        external: services.filter(service => service.section === 'external')
          .length,
        internal: services.filter(service => service.section === 'internal')
          .length,
      },
      confidence: {
        high: services.filter(service => service.confidence === 'high').length,
        needsHuman: services.filter(service => service.confidence !== 'high')
          .length,
      },
      services,
    };

    writeFileSync(
      path.join(OUT, `${documentStem(file)}.yaml`),
      BANNER +
        yaml.dump(document, { lineWidth: 100, noRefs: true, quotingType: '"' }),
      'utf8'
    );

    summary.push({
      document: file,
      services: services.length,
      high: document.confidence.high,
      needsHuman: document.confidence.needsHuman,
      withFees: services.filter(service => service.fees.length > 0).length,
      withRequirements: services.filter(
        service => service.requirements.length > 0
      ).length,
      withTotal: services.filter(service => service.total).length,
    });

    process.stdout.write(
      `${String(services.length).padStart(3)} services  ` +
        `${String(document.confidence.high).padStart(3)} high  ` +
        `${file}\n`
    );
  }

  const totals = summary.reduce(
    (accumulator, row) => ({
      services: accumulator.services + row.services,
      high: accumulator.high + row.high,
      needsHuman: accumulator.needsHuman + row.needsHuman,
      withFees: accumulator.withFees + row.withFees,
      withRequirements: accumulator.withRequirements + row.withRequirements,
      withTotal: accumulator.withTotal + row.withTotal,
    }),
    {
      services: 0,
      high: 0,
      needsHuman: 0,
      withFees: 0,
      withRequirements: 0,
      withTotal: 0,
    }
  );

  writeFileSync(
    path.join(INVENTORY, 'charter-extraction-report.yaml'),
    BANNER +
      yaml.dump(
        { totals, documents: summary },
        { lineWidth: 100, noRefs: true }
      ),
    'utf8'
  );

  process.stdout.write(
    `\n${totals.services} services · ${totals.high} high confidence · ` +
      `${totals.needsHuman} need a human\n` +
      `${totals.withRequirements} with requirements · ${totals.withFees} with a fee · ` +
      `${totals.withTotal} with a total row\n`
  );
}

main();
