/**
 * The freshness report, and the check-date baseline.
 *
 *   npm run freshness           write inventory/freshness-report.md
 *   npm run freshness -- --baseline   also rewrite inventory/check-dates.yaml
 *
 * ⚠️ **The baseline is not rewritten by default, and that is the point.**
 * CONT-401 criterion 5 says a page is never made to look fresh by advancing its
 * check date without somebody re-checking it. The baseline is what a test
 * compares against; regenerating it on every run would make that test agree
 * with whatever was just typed.
 *
 * 🔴 This script NEVER writes into content/. It reports.
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { globSync } from 'node:fs';
import path from 'node:path';
import yaml from 'js-yaml';

const ROOT = path.resolve(import.meta.dirname, '..');
const TODAY = new Intl.DateTimeFormat('en-CA', {
  timeZone: 'Asia/Manila',
}).format(new Date());

const freshness = JSON.parse(
  readFileSync(path.join(ROOT, 'config', 'freshness.config.json'), 'utf8')
);

const entries = [];
for (const rel of globSync('content/**/index.yaml', { cwd: ROOT }).sort()) {
  const manifest = yaml.load(readFileSync(path.join(ROOT, rel), 'utf8'));
  for (const page of manifest.pages ?? []) {
    entries.push({ manifest: rel, ...page });
  }
}

const DAY = 86_400_000;
const ageOf = date =>
  Math.round(
    (Date.parse(`${TODAY}T00:00:00Z`) - Date.parse(`${date}T00:00:00Z`)) / DAY
  );

const rows = entries.map(entry => {
  const declared = freshness.classes[entry.dataClass];
  const age = ageOf(entry.lastCheckedAt);
  const state =
    age < 0
      ? 'undated'
      : age > declared.cadenceDays
        ? 'stale'
        : age > declared.cadenceDays * 0.9
          ? 'due'
          : 'fresh';
  return { ...entry, age, cadence: declared.cadenceDays, state };
});

const overdue = rows.filter(
  row => row.state === 'stale' || row.state === 'due'
);
const broken = rows.filter(row => row.state === 'undated');

const byClass = Object.keys(freshness.classes).map(name => ({
  name,
  cadence: freshness.classes[name].cadenceDays,
  pages: rows.filter(row => row.dataClass === name).length,
  overdue: overdue.filter(row => row.dataClass === name).length,
}));

const lines = [
  '<!-- Generated by scripts/freshness.mjs — do not edit by hand. -->',
  '',
  '# Freshness report',
  '',
  `Generated **${TODAY}**, against ${rows.length} published pages in ${new Set(rows.map(r => r.manifest)).size} manifests.`,
  '',
  '## By data class',
  '',
  '| Class | Cadence | Pages | Past cadence or due |',
  '| --- | --- | --- | --- |',
  ...byClass.map(
    c => `| \`${c.name}\` | ${c.cadence} days | ${c.pages} | ${c.overdue} |`
  ),
  '',
  '## Pages needing a review',
  '',
];

if (overdue.length === 0) {
  lines.push(
    'None. **That is not the same as everything having been checked** — every page in this',
    'repository still carries its original check date, and `lastReview` is `null` on all of',
    `them. Nothing has been re-checked since it was written; nothing is yet OLD enough to be`,
    'due. The first cadence to bite is `emergency`, at 90 days.',
    ''
  );
} else {
  lines.push(
    '| Page | Class | Last checked | Age | State |',
    '| --- | --- | --- | --- | --- |'
  );
  for (const row of overdue.sort((a, b) => b.age - a.age)) {
    lines.push(
      `| \`${row.slug}\` | \`${row.dataClass}\` | ${row.lastCheckedAt} | ${row.age} days | **${row.state}** |`
    );
  }
  lines.push('');
}

if (broken.length > 0) {
  lines.push(
    '## 🔴 Check dates in the future',
    '',
    'A check date later than today is not a degree of staleness. It is a defect.',
    '',
    ...broken.map(row => `- \`${row.slug}\` — ${row.lastCheckedAt}`),
    ''
  );
}

lines.push(
  '## Reviews recorded',
  '',
  `${rows.filter(row => row.lastReview).length} of ${rows.length} pages carry a \`lastReview\`.`,
  '',
  'A review records the ROLE that did it and the date. A check date that moves without one',
  'is a falsified record, and `src/lib/content-records.test.ts` fails the build on it by',
  'comparing against `inventory/check-dates.yaml`.',
  ''
);

writeFileSync(
  path.join(ROOT, 'inventory', 'freshness-report.md'),
  lines.join('\n')
);
console.log(
  `freshness: ${rows.length} pages · ${overdue.length} past cadence or due · ${broken.length} future-dated`
);

if (process.argv.includes('--baseline')) {
  const baseline = {
    note: 'The check date each page carried when this baseline was last taken deliberately. src/lib/content-records.test.ts fails the build when a lastCheckedAt moves past its baseline without a lastReview added in the same change — that is what stops a page being made to look fresh without somebody re-checking it. Regenerate ONLY as a deliberate act, in a diff somebody reviews: npm run freshness -- --baseline',
    takenAt: TODAY,
    pages: Object.fromEntries(
      rows
        .map(row => [
          `${path.dirname(row.manifest).replace(/^content\//, '')}/${row.slug}`,
          row.lastCheckedAt,
        ])
        .sort(([a], [b]) => a.localeCompare(b))
    ),
  };
  writeFileSync(
    path.join(ROOT, 'inventory', 'check-dates.yaml'),
    `# Generated by scripts/freshness.mjs --baseline — regenerate only deliberately.\n${yaml.dump(baseline, { lineWidth: 100, noRefs: true, quotingType: '"' })}`
  );
  console.log('  wrote inventory/check-dates.yaml');
}
